### ISSUE TITLE
Command to force bypass cooldowns

### ISSUE THREAD

**Issue by Cale111** [Osiris-Team/AutoPlug-Client#106]
**Importance:** 6

**Problem:**
For example, right now, if you change the config option for what version of Minecraft to auto-update while the server is still in the cooldown, you have to go change the cooldown to 0, then turn on the server, then change the cooldown back to what it was before.

**Solution:**
This process could be much faster if you could enter a command to force an update anyway.

**Comment by Osiris-Team** [comment]
I agree. Commands could look like this:
 `.check plugins` or `.check server` and the force variant: `.force-check plugins` or `.force-check server` etc.

**Comment by Osiris-Team** [comment]
added the changes, will be available in next beta/stable release
