### ISSUE TITLE
Ability use AutoPlug remotely

### ISSUE THREAD

**Issue by RehanPlayz** [Osiris-Team/AutoPlug-Client#119]
**Importance:** 5/10 (Enter a value between 0-10, where 10 is the most important thing on the planet)

**Problem:**
Some hosts don't allow changing the startup command 

**Solution:**
Describe your solution to the problem and any alternative solutions.
 You run the program on your PC and it connects to the server through sftp and updates everything

**Comment by Osiris-Team** [comment]
If u got access via sftp you should be able to replace the server jar?

**Comment by Osiris-Team** [comment]
Closing bc of no response
