### ISSUE TITLE
pufferfish auto-update support

### ISSUE THREAD

**Issue by Keopsfenks** [Osiris-Team/AutoPlug-Client#136]

**Comment by Osiris-Team** [comment]
Sure thing. Here is a lib that I want to implement to support pufferfish and other server jars, but don't have time to: https://www.spigotmc.org/resources/mcserverupdater.98003/
You could implement it if you want. I already asked the developer of that lib if he/she wanted to, but didn't look like it :/

**Comment by Keopsfenks** [comment]
> Sure thing. Here is a lib that I want to implement to support pufferfish and other server jars, but don't have time to: https://www.spigotmc.org/resources/mcserverupdater.98003/ https://github.com/HSGamer/MCServerUpdater You could implement it if you want. I already asked the developer of that lib if he/she wanted to, but didn't look like it :/

So can I run it with autoplug?

**Comment by Keopsfenks** [comment]
Two jars together.

**Comment by Keopsfenks** [comment]
> U could give it a try, but It would be way easier implementing that lib into AutoPlugs source code.

I get it, thank you for answering.

As for the source incident, I don't know java, I hope you add a day of good times^^
