### ISSUE TITLE
HtmlUnit javascript error prevents plugin update downloading

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/AutoPlug-Client#14]
We are facing some issues downloading updates for plugins. 
That issue is related to a dependency AutoPlug is using and some changes spigot did to its download page.
At the moment there are multiple ways to fix our issue.
1. Fix the core of our dependency (would take ages; for further details see this: https://github.com/HtmlUnit/htmlunit/issues/201).
2. Download jars located on spigot via spiget api (Details: https://github.com/Osiris-Team/AutoPlug-Client/issues/21)

**Comment by bobhenl** [comment]
Hi, how it looks?

**Comment by Osiris-Team** [comment]
@bobhenl Still working on the engine implementation. Its indeed a lot of work

**Comment by Has-X** [comment]
i w a n t a u t o p l u g

**Comment by GabrielTK** [comment]
Is work on that being done on a public branch? Would love to contribute :)

**Comment by Osiris-Team** [comment]
@GabrielTK  Yes but sadly I stopped working on that a while ago because its basically an insanely big amount of work for me alone.
Here is some more information: https://github.com/HtmlUnit/htmlunit/issues/201#issuecomment-683276644

**Comment by JW6677** [comment]
Is there a fix for this yet? Looks like a really cool and useful plugin!

**Comment by Osiris-Team** [comment]
> Is there a fix for this yet? Looks like a really cool and useful plugin!

Yes we got a partial fix. AutoPlug will be able to update all plugins except those which are hosted on external platforms :/ See https://github.com/Osiris-Team/AutoPlug-Client/issues/21
If you want to get notified when the update is ready join our discord group: https://discord.com/invite/GGNmtCC

**Comment by Osiris-Team** [comment]
It's currently possible to download external plugins even over spiget...
So HtmlUnit got pretty much unnecessary at this point.
I'll remove the dependency and comment out all the stuff related to it. Maybe I'll need it someday...
