### ISSUE TITLE
Option to stop AutoPlug too automatically when using a stop button on a hosting or when using .stop command

### ISSUE THREAD

**Issue by Minionguyjpro** [Osiris-Team/AutoPlug-Client#145]
**Importance:** 0/10
6
**Problem:**
When using the stop button on a hosting with for example Pterodactyl panel, it stops the MC server but not AutoPlug.

**Solution:**
Add an option to when the stop button is pressed it stops AutoPlug too automatically, and not make you need to enter ``.stop both`` too. And with the ``.stop`` command to auto stop AutoPlug too.

**Comment by Osiris-Team** [comment]
![image](https://user-images.githubusercontent.com/59899645/157890326-d68820e0-407b-487c-8ab5-e255b113afb8.png)
Already exists in the general config ;)

**Comment by Minionguyjpro** [comment]
> ![image](https://user-images.githubusercontent.com/59899645/157890326-d68820e0-407b-487c-8ab5-e255b113afb8.png) Already exists in the general config ;)

👍
