### ISSUE TITLE
Autoplug can't update velocity plugins. Add support for reading velocity-plugin.json

### ISSUE THREAD

**Issue by Micim987** [Osiris-Team/AutoPlug-Client#158]
**Importance:** 5/10

**Problem:**
Autoplug is unable to update Velocity plugins because velocity plugins use a `velocity-plugin.json` instead of a `plugin.yml`

**Solution:**
Make it so that when the server type is set to velocity it looks for a `velocity-plugin.json` instead of a `plugin.yml` file and pulls the version from there instead.

**Comment by Osiris-Team** [comment]
supported in 5.11.0
