### ISSUE TITLE
Disable >.... before ran commands

### ISSUE THREAD

**Issue by Erisfiregamer1** [Osiris-Team/AutoPlug-Client#167]
**Importance:** 3/10

**Problem:**
I don't like seeing >.... before every command I run on the console. I'd like to disable it somehow.
**Solution:**
Disable the >.... before every terminal-ran command.

**Comment by Osiris-Team** [comment]
can u send a screenshot?
i dont have a > before my commands

**Comment by Erisfiregamer1** [comment]
![image](https://user-images.githubusercontent.com/54373833/170984879-5840e357-4240-449c-9c6c-dea407fcd266.png)

**Comment by Minionguyjpro** [comment]
I think this is just how your server hosting/software has set this up.

**Comment by Erisfiregamer1** [comment]
It's not. This didn't happen before installing AutoPlug (yes, this is a fully self-hosted setup).

**Comment by Minionguyjpro** [comment]
> It's not. This didn't happen before installing AutoPlug (yes, this is a fully self-hosted setup).

Weird. Isn't it because of plugins are running?

**Comment by Erisfiregamer1** [comment]
Which type of plugins, Panel plugins or Minecraft plugins?

**Comment by Minionguyjpro** [comment]
> Which type of plugins, Panel plugins or Minecraft plugins?

All?

**Comment by Osiris-Team** [comment]
Cannot reproduce your issue:
![image](https://user-images.githubusercontent.com/59899645/171285482-ca570521-289e-4ce0-94d6-af675aac53b4.png)
Feel free to reopen if you can provide more details for me to reproduce.

**Comment by Osiris-Team** [comment]
It works as intended on a regular terminal on Linux (+distros), Macos and Windows.
Further discussion on this so-called "issue" is nonsense. I hardly believe it is possible to fix this by coding something into AutoPlug, ask pterodactyl devs for support or find a developer that is interested in fixing this.
