### ISSUE TITLE
Support Quilt (server software / mod-loader) for auto-updating

### ISSUE THREAD

**Issue by Skidamek** [Osiris-Team/AutoPlug-Client#172]
**Importance:** 5/10

**Problem:**
Can not auto update/download quilt mod loader
https://quiltmc.org/

**Solution:**
Implement auto-updating quilt to AutoPlug

**Comment by Skidamek** [comment]
I am working on it.

**Comment by Skidamek** [comment]
Quilt's dead

**Comment by Minionguyjpro** [comment]
Quilt is alive as far as I can tell, but this would have to be implemented into the MCServerUpdater library and is hard since differently from Fabric, it has an additional JAR that actually downloads the final server JAR.
