### ISSUE TITLE
Support Pufferfish+ and purpur variant for Auto Update

### ISSUE THREAD

**Issue by Mukul1127** [Osiris-Team/AutoPlug-Client#188]
**Importance:** 6/10

**Problem:**
Can not auto update/download pufferfish / pufferfish+ paper fork

**Solution:**
Implement auto-updating pufferfish / pufferfish+ to AutoPlug

**Comment by Osiris-Team** [comment]
Pufferfish is already supported. 
Whats pufferfish+?

**Comment by Mukul1127** [comment]
their website says "Pufferfish Plus is our improved version of Pufferfish, which includes enterprise support and additional async features, such as an async entity tracker and an async pathfinding system. In benchmarks, it is around 25-30% faster than the standard version of Pufferfish." Link: https://pufferfish.host/downloads

**Comment by Mukul1127** [comment]
also what about Pufferfish+ Purpur

**Comment by Mukul1127** [comment]
nvm

**Comment by Mukul1127** [comment]
oops

**Comment by Osiris-Team** [comment]
Yeah those versions can be added

**Comment by Mukul1127** [comment]
thanks

**Comment by Osiris-Team** [comment]
Its not available yet though. Working on it.
