### ISSUE TITLE
Updating Autoplug-Client: Comparing hashes failed

### ISSUE THREAD

**Issue by Chem0908** [Osiris-Team/AutoPlug-Client#206]
<details>
  <summary>Show log</summary>
  
```log
[02-01-2023 12:09:38][AP][DEBUG][TaskDownload] Comparing hashes (SHA-256). Result: true Excepted: f23dc5d9f053c3800d8469830bd00788bd1ad365e671fda790241e0272ed0fd7 Actual:F23DC5D9F053C3800D8469830BD00788BD1AD365E671FDA790241E0272ED0FD7
```
</details>

**Expected**
That the compared hashes matches and autplug dont stop

**Actual**
The hashes do not match because the compare is case sensitive

**Steps**
(Optional) Run Autoplug-Client on linux for minecraft 1.19.2 fabric with an different version to it that is available

**Screenshots**
![image](https://user-images.githubusercontent.com/60881022/210230363-ca79c9b0-f73e-442a-9a33-210701f0bd75.png)

**Comment by Osiris-Team** [comment]
`... result: true...` means that the hashes are equal, thus the self-updater proceeds and installs the update, which is why you see the `See you soon!` message.
