### ISSUE TITLE
[FAQ page] Link to install client on server host broken

### ISSUE THREAD

**Issue by Illyrius666** [Osiris-Team/AutoPlug-Client#209]
**That specific link on the faq returns me 404 page not found.**

_"Can I install AutoPlug Client on a server host?
Yes! For instructions on how to do so, please read [How To - Install AutoPlug Client on a Server Host](https://github.com/Osiris-Team/AutoPlug-Client/blob/master/docs/LinkToPageTBD)."_

**Comment by Osiris-Team** [comment]
@lkkuma guess this one is for you?
