### ISSUE TITLE
Allow/Deny auto restart when players are online

### ISSUE THREAD

**Issue by Minionguyjpro** [Osiris-Team/AutoPlug-Client#211]
**Importance:** 0/10
2
**Problem:**
I don't really have a problem with it, others may have it.

**Solution:**
Add a function in the ``restarter.yml`` to allow or deny an automatic restart when players are on the server for that moment.

**Comment by Osiris-Team** [comment]
Yeah I remember that you already created that issue: #137
Closing bc of duplicate.

**Comment by Minionguyjpro** [comment]
Ok, but can you also respond to it???

**Comment by Osiris-Team** [comment]
@Minionguyjpro I stopped adding new features to autoplug a while ago.
You can either add it yourself, or hire a developer, or hire me. Id do it for 50€
