### ISSUE TITLE
Your commands to install Autoplug in linux do not work, due to the link to the raw file being outdated? or incorrectly formatted?

### ISSUE THREAD

**Issue by harryeffinpotter** [Osiris-Team/AutoPlug-Client#238]
This line does not work on linux:
curl -o AutoPlug-Client.jar https://github.com/Osiris-Team/AutoPlug-Releases/raw/master/beta-builds/AutoPlug-Client.jar

This line does:
curl -o AutoPlug-Client.jar https://raw.githubusercontent.com/Osiris-Team/AutoPlug-Releases/master/beta-builds/AutoPlug-Client.jar

I'm guessing git changed how they store raw files and this probably used to work.
I noticed the file result to your suggested manual install commands was 0 bytes and dug futher.

Hope this helps!

**Comment by Minionguyjpro** [comment]
> @harryeffinpotter Great, yeah, weirdly enough, in the browser both links work. Thanks, will add it to the site once I got time to work on autoplug again ;)

Probably the first link redirects to the second one and curl isn't set up to follow the redirects, while a browser does?

**Comment by Minionguyjpro** [comment]
> > @harryeffinpotter Great, yeah, weirdly enough, in the browser both links work. Thanks, will add it to the site once I got time to work on autoplug again ;)
> 
> Probably the first link redirects to the second one and curl isn't set up to follow the redirects, while a browser does?

Yeah this is the case. I also ran into the same 0 byte issue with curl with the first link, but if I'd run it with the ``-L`` parameter then it works and downloads the file correctly. That first link just redirects to the second one, thus if you'd use curl without it making sure to follow redirects then the generated file will be zero bytes. So that it doesn't work is just due to redirects...

**Comment by Osiris-Team** [comment]
fixed, will update web in a bit

**Comment by harryeffinpotter** [comment]
> > > @harryeffinpotter Great, yeah, weirdly enough, in the browser both links work. Thanks, will add it to the site once I got time to work on autoplug again ;)
> > 
> > 
> > Probably the first link redirects to the second one and curl isn't set up to follow the redirects, while a browser does?
> 
> Yeah this is the case. I also ran into the same 0 byte issue with curl with the first link, but if I'd run it with the `-L` parameter then it works and downloads the file correctly. That first link just redirects to the second one, thus if you'd use curl without it making sure to follow redirects then the generated file will be zero bytes. So that it doesn't work is just due to redirects...

AHH I always forget the dang argument to follow redirects. My man.

**Comment by harryeffinpotter** [comment]
So 

`curl -Lo AutoPlug-Client.jar https://github.com/Osiris-Team/AutoPlug-Releases/raw/master/beta-builds/AutoPlug-Client.jar`

would work, yeah?

**Comment by harryeffinpotter** [comment]
oope, he said he fixed it, was just curious for my own sake.

**Comment by harryeffinpotter** [comment]
> `curl -Lo AutoPlug-Client.jar https://github.com/Osiris-Team/AutoPlug-Releases/raw/master/beta-builds/AutoPlug-Client.jar`

indeed it does fix, good call.
