### ISSUE TITLE
Official Docker Image (I Could Make It)

### ISSUE THREAD

**Issue by Minionguyjpro** [Osiris-Team/AutoPlug-Client#239]
**Importance:** 5/10

**Problem:**
Some people may prefer using Docker to run a Minecraft server to isolate it and to easily like manage things in a prebuilt environment. There is currently no official Docker image.

**Solution:**
Make a Docker image for different Java versions (8, 11, 16, 17 and 21) which uses Eclipse Temurin. We could use Docker Compose to customize things like ports and paths. It'd be possible to make tags like ``7.5.18-jdk11``, ``7.5.16-jdk17`` etc. though that will cost work and since it can only download the latest release without version it may be a bit of hassle (though there's a catch, maybe we can extract the version from the JAR in a GitHub Action automatically on release somewhere). Otherwise we just do ``11`` or ``jdk11`` tags that always point to the latest release. Since you have an auto updater it can already self update AutoPlug to a newer version in the container if it's older. I am already trying to create something for this right now.

**Comment by Osiris-Team** [comment]
There is already support for this, see readme under community projects.

**Comment by Minionguyjpro** [comment]
I see, but it hasn't been updated in a year and using Docker Compose we could add more configuration probably.
