### ISSUE TITLE
Adding PandaSpigot to Server Software

### ISSUE THREAD

**Issue by Minionguyjpro** [Osiris-Team/AutoPlug-Client#263]
**Importance:** 7/10

**Problem:**
I would like to use PandaSpigot along with AutoPlug, which is a well maintained fork of Paper for Minecraft 1.8.8.

**Solution:**
Add the feature, it shouldn't be so hard since there is an API for it available at https://downloads.hpfxd.com which seems based on OpenAPI and using GET requests stuff can be retrieved.

**Comment by Minionguyjpro** [comment]
I will try looking into this, if you can give me the direction of the existing ones that use this maybe. I am pretty sure Paper or something itself also uses this API to retrieve stuff?

**Comment by Minionguyjpro** [comment]
Found out the external MCServerUpdater library is responsible for this, I will try and see if I can make changes at them and then PR them into there.

**Comment by Minionguyjpro** [comment]
Changes are made and it's working! I hope it to get merged into MCServerUpdater soon. As soon as that library gets a new release, the only thing that needs to happen here is to upgrade the version of the library linked to the AutoPlug-Client project!

**Comment by Minionguyjpro** [comment]
Great! My PR got merged. Now it's pure time to wait for the next release of their library.

**Comment by Osiris-Team** [comment]
@Minionguyjpro nice while you are at it, if you are interested take a look a the other open issues over there

**Comment by Minionguyjpro** [comment]
As we know this has now been integrated by #264
