### ISSUE TITLE
[Feature Request] Update Plugins via GitHub

### ISSUE THREAD

**Issue by D1yt** [Osiris-Team/AutoPlug-Client#27]
Would you be able to add support to updating plugins through GitHub instead of SpiGet?
Maybe with 3 options like stable, unstable and live?

(Of course fixing updating plugins is higher priority)

**Comment by Osiris-Team** [comment]
@D1yt Yeah I think that should be possible.
Would be great if you could do some research on how to realize your idea.

**Comment by Osiris-Team** [comment]
@D1yt There's a new feature in v0.9+ where you can set static URLs, so I'm closing this for now.
