### ISSUE TITLE
AutoPlug Stop with /stop

### ISSUE THREAD

**Issue by BLACK4585** [Osiris-Team/AutoPlug-Client#36]
Since in many server panels the server is still shown as online when anything is running, there are some complications with AutoPlug. When the "Stop" button is executed, only the server is stopped, not AutoPlug. In short: So that AutoPlug is also restarted, the question is whether you can add the function that AutoPlug is also stopped after the server has stopped? So also with /stop?
Since you will not always need this, it would be quite good if you could switch this function on and off in the Config.

Thank you,
BLACK

**Comment by Osiris-Team** [comment]
Available in latest beta ;)
