### ISSUE TITLE
Execute AutoPlug commands in the game (maybe with GUI)

### ISSUE THREAD

**Issue by BLACK4585** [Osiris-Team/AutoPlug-Client#39]
It would be good to be able to execute AutoPlug commands in the game as well.

**Comment by Osiris-Team** [comment]
Maybe also implement an in-game GUI for that.

**Comment by Osiris-Team** [comment]
Just released the AutoPlug-Plugin, which does exactly this: https://www.spigotmc.org/resources/autoplug-plugin.95568/
