### ISSUE TITLE
Auto-Updating for Github-Releases through their API

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/AutoPlug-Client#52]
https://docs.github.com/en/rest/reference/repos#releases

**Comment by Osiris-Team** [comment]
This could also be implemented into the plugins and server updater.
We could search through github for the author and the plugins/servers name and check if the repository has packages.

**Comment by Osiris-Team** [comment]
Rate limit hits different

**Comment by Anarchick** [comment]
I'm in favor of this. Skipt community is huge and not really present on spigot / bukkit. We use Github for the mojority of us. The Skript bukkit's page is out of date, and theyre are 2 main versions of Skript for mc1.8 with the Gio's fork and the official 
 from SkriptLang. Both only donwloadable on Github.

**Comment by Osiris-Team** [comment]
@Anarchick currently experimenting with the github releases api and its seems like this could really be a thing.
The users would have to enter the repository name manually though like 'Osiris-Team/AutoPlug-Client'.

**Comment by Osiris-Team** [comment]
now available in v5.4
