### ISSUE TITLE
Name of the AutoPlug Jar can be renamed

### ISSUE THREAD

**Issue by BLACK4585** [Osiris-Team/AutoPlug-Client#70]
Since some hosters can only execute predefined names for their own jars, e.g. custom.jar, these hosters cannot execute an AutoPlug-Client.jar. It would therefore be good if you could permanently enter and save the desired name of the client in the config, so that AutoPlug knows itself which file it is and does not start itself all the time and automatically renames the new, downloaded jar when replacing the old one with the name specified in the config.

**Comment by Osiris-Team** [comment]
Yep agreed. Already got an idea how to achieve this. We could simply look inside of the jar and search for a autoplug.properties file. If it has none, its not the AutoPlug-Client, but probably the server jar.

**Comment by Osiris-Team** [comment]
Self-Updater must be set to use the current file name, instead of AutoPlug-Client.jar
