### ISSUE TITLE
doesn't work UTF-16 Encoding

### ISSUE THREAD

**Issue by Davide00** [Osiris-Team/AutoPlug-Client#72]
hi, just your plugin doesn't read the UTF-16 Encoding, on console with tellraw
![image](https://user-images.githubusercontent.com/25281342/125169354-0b95f900-e1aa-11eb-83db-77045f192f38.png)

**Comment by Osiris-Team** [comment]
@Davide00 how is that related to utf-16?

**Comment by Osiris-Team** [comment]
also why would you use utf16 encoding, when the restart config is in utf8?

**Comment by Osiris-Team** [comment]
Guess this could be easily fixed by using UTF-16 to decode the user input and pass it over to the server.
Going to give it a try tomorrow.

**Comment by Osiris-Team** [comment]
Just did some research and apparrently the java `String` is already UTF16 encoded by default.
Im closing this issue for now since there shouldnt be a problem.
https://stackoverflow.com/questions/6622226/check-if-a-string-is-valid-utf-8-encoded-in-java
