### ISSUE TITLE
How to select a "universe"

### ISSUE THREAD

**Issue by Luismm2311** [Osiris-Team/AutoPlug-Client#81]
In order to have more organized the root directory of my server, I have a carpet for each world and until now I used the argument `--universe ./world1`.
But I'm not sure on ho to doit with AutoPlug
I tried using the `arguments: `section on the `general-config.yml` file like this:
```
arguments: 
      # If you were using arguments, add them to the list below.
      # Arguments are passed after the '-jar <file-name>.jar' part. Example: '... -jar server.jar <arguments>'
      # They can be specific to the server software you are using.
      # Note that typos/wrong arguments may prevent your server from starting!
      # More on this topic:
      # https://minecraft.fandom.com/wiki/Tutorials/Setting_up_a_server
      # https://bukkit.gamepedia.com/CraftBukkit_Command_Line_Arguments
      # https://www.spigotmc.org/wiki/start-up-parameters
      enable: true
      list: 
        - nogui
        - universe /home/minecraftuser/minecraftdir/world1
    restart-on-crash: true
```
But it didn’t worked.

I am using Ubuntu Server 20.10, java 16.0.2 and PaperMC

**Comment by Osiris-Team** [comment]
Did you try exactly `universe ./world1` instead of `universe /home/minecraftuser/minecraftdir/world1`?

**Comment by Osiris-Team** [comment]
I dont see a reason why this shouldnt work though :/ If you got some error messages it would help.

**Comment by Luismm2311** [comment]
> Did you try exactly `universe ./world1` instead of `universe /home/minecraftuser/minecraftdir/world1`?

I tried it and didn’t worked



> I dont see a reason why this shouldnt work though :/ If you got some error messages it would help.

It doesn’t show any error code, it just creates a new world on de root directory

**Comment by Osiris-Team** [comment]
Ok sry to hear that, but without more information, there is not much I can do, so imma close this for now.
Feel free to reopen when u got more helpful details.
