### ISSUE TITLE
Feature Request: Download new Plugins

### ISSUE THREAD

**Issue by D1yt** [Osiris-Team/AutoPlug-Client#85]
Hey, I would also like to be able to download plugins by pressing a button next to the showcased/searchable plugins on your website or download them with a command (providing the spigot ID, name and author or a static link to an external site).

This would save alot of time when still setting up a server and replace additional download plugins.

**Comment by Osiris-Team** [comment]
Similar feature is already in todo here: https://github.com/Osiris-Team/AutoPlug-Client/issues/17
