### ISSUE TITLE
custom-author gets ignored if author is empty

### ISSUE THREAD

**Issue by Blank517** [Osiris-Team/AutoPlug-Client#87]
In plugins-config.yml if the plugin.author is empty and/or impossible to retrieve from plugin.yml than plugin.custom-author gets ignored.

**Comment by Osiris-Team** [comment]
Oh thats still in AutoPlug ups! Forgot to remove that. Enter a spigot or bukkit id instead. Going to remove this in the next update.

**Comment by Blank517** [comment]
Sorry if I reopen but i have to say that even with an id provided it doesn't work because your plugin.yml parser update the value of author every time and is a value needed to download the plugin. So until the next update we can only exclude the plugin to not get warnings (or errors? i don't remember now) in logs

**Comment by Osiris-Team** [comment]
@Blank517 should be fixed now in 5.0.4
