### ISSUE TITLE
Disabling web features

### ISSUE THREAD

**Issue by Cale111** [Osiris-Team/AutoPlug-Client#97]
**Importance:** 7

**Problem:**
On startup, AutoPlug asks for a server key and doesn't continue until something is entered, blocking a restart if it self-updates.

**Solution:**
Either have the option to disable the web features in the config, or have a timeout for entering the server key.

**Comment by Osiris-Team** [comment]
You can enter something random at the first start (or in the general config) to fix this.
Also, individual web features can be disabled in the web-config.yml.
