### ISSUE TITLE
Support to minecraft on a Raspberry Pi (pinecraft)

### ISSUE THREAD

**Issue by ThEnchanted** [Osiris-Team/AutoPlug-Client#98]
Could you add support for Minecraft on Raspberry Pi?

I'm one of the users of it but the interface from a terminal is a bit clunky for me

**Comment by Osiris-Team** [comment]
Ok just to make sure I understood.
AutoPlug is working fine on Raspberry Pi, but the terminal output when running AutoPlugs before startup tasks is a bit buggy?
In that case you can disable live-tasks in the tasks config file.
Sadly I am using a third-party dependency (Jansi and Jline) to display terminal messages, so if these do not support Raspberry Pi there won't be in AutoPlug either.
